extends Node

@warning_ignore("unused_signal")
signal player_pos_updated(pos: Vector2)
@warning_ignore("unused_signal")
signal zoom_in_requested()
@warning_ignore("unused_signal")
signal zoom_out_requested()
@warning_ignore("unused_signal")
signal run_ended(won: bool, cause: String)
@warning_ignore("unused_signal")
signal sound_emitted(world_position: Vector2, pixel_radius: float)
@warning_ignore("unused_signal")
signal level_ready()
@warning_ignore("unused_signal")
signal loadout_rolled(loadout: RunLoadout)
